export const queryKeys = {
  club: ['club'] as const,
  dashboard: ['dashboard'] as const,
  activeCandidate: ['candidate', 'active'] as const,
  bookQueue: ['me', 'book-queue'] as const,
  authSession: ['session', 'me'] as const,
  currentUser: ['session', 'me'] as const,
  currentUserReadingHistory: ['session', 'me', 'reading-history'] as const,
  twoFactorQrCode: ['session', 'two-factor', 'qr-code'] as const,
  twoFactorSecretKey: ['session', 'two-factor', 'secret-key'] as const,
  twoFactorRecoveryCodes: ['session', 'two-factor', 'recovery-codes'] as const,
  genres: ['genres'] as const,
  members: ['members'] as const,
  member: (id: number) => ['members', id] as const,
  cycles: ['cycles'] as const,
  cycle: (cycleNumber: string | number) => ['cycles', String(cycleNumber)] as const,
  openLibraryCovers: (title: string, author: string) =>
    ['books', 'open-library', 'covers', title, author] as const,
  meeting: (id: string | number) => ['meetings', String(id)] as const,
}
